# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore: 
      - "main"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: "20"

    - name: Install dependencies
      run: |
        # python -m pip3 install --upgrade pip
        sudo npm install -g aws-cdk
        sudo apt install awscli
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pycodestyle
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # echo ${{ vars.TEST_VARIABLE }}
        # echo ${{ vars.TEST_SECRET }}
        pycodestyle projects/*/*/*.py
    - name: Test with pytest
      run: |
        pytest
